;METADATA=(Diff=true, UseCommands=true)
[ScalabilityGroups]
sg.ResolutionQuality=100
sg.SecondaryResolutionQuality=100
sg.ViewDistanceQuality=2
sg.AntiAliasingQuality=4
sg.ShadowQuality=0
sg.GlobalIlluminationQuality=0
sg.ReflectionQuality=4
sg.PostProcessQuality=4
sg.TextureQuality=2
sg.EffectsQuality=4
sg.FoliageQuality=4
sg.ShadingQuality=4
sg.LandscapeQuality=4
sg.BloomQuality=0
sg.CharacterTextureQuality=2
sg.DepthOfFieldQuality=4
sg.EffectsTextureQuality=4
sg.LensFlareQuality=4
sg.MeshQuality=4
sg.MotionBlurQuality=0
sg.ParticleSpawnRateQuality=4
sg.TextureFilteringQuality=2
sg.WorldTextureQuality=2

[/Script/WDGame.WDUserSettings]
CustomProjectVersion=2
ClanTag=SEXI
bIsStreamerModeEnabled=False
bIsAnonymousModeEnabled=False
bIsChatboxDisabled=False
bIsChatProfanityFilterEnabled=False
bShowIdentityIcon=True
bIsFPSTrackerEnabled=False
bIsLatencyTrackerEnabled=False
AimingFovMode=Independent
FirstPersonMeshFieldOfViewScale=0.444444
FirstPersonVehicleFieldOfView=83.000000
ThirdPersonVehicleFieldOfView=110.000000
KillfeedFilter=All
bIsAdaptiveCrosshairEnabled=True
BipodDeployMode=Automatic
bIsPictureInPictureScopeEnabled=False
NameplateBackgroundOpacity=0.000000
bAlwaysDisplayAllQuickSlots=True
bIsMapRotationEnabled=False
bInvertMapZoom=False
bIsMapZoomSynced=True
VehicleFreelookOnByDefault=False
VehicleFirstPersonCameraSensitivity=1.000000
VehicleThirdPersonCameraSensitivity=1.000000
SlowWalkSpeed=Slow
VehicleTransmissionType=AUTO
EnableFreeCursorState=True
FreeCursorSensitivity=1.000000
AudioInputDevice="{0.0.1.00000000}.{4a02792e-7e33-4f78-8992-ec81b1d2bae9}"
bIsVoiceChatEnabled=True
bIsProximityVoiceChatEnabled=True
bIsSquadVoiceChatEnabled=True
bTinnitusAudioEnabled=True
bIsSpatialAudioEnabled=True
RadioMusicVolume=0.500000
MicrophoneVolume=1.000000
MouseADSSensitivityMultiplier=0.760000
VehicleWeaponMouseSensitivityMultiplier=1.000000
GamepadADSSensitivityMultiplier=0.500000
LandVehicleSensitivityMultiplier=2.000000
AirVehicleSensitivityMultiplier=0.480000
AimingFovSensitivityMode=Relative
AimingFovSensitivityTransitionType=AimingAlpha
AimingSensitivityRelativeCoefficient=100.000000
bInvertYAxisInfantry=False
bInvertYAxisLandVehicles=False
bInvertYAxisHelicopters=False
bUseHOTASHelicopters=False
bCollectiveSelfCentering=False
bFlightAssistsEnabled=False
bHeliAssistStabilityEnabled=False
bHeliAssistAutoHoverEnabled=False
bHeliAssistEnvelopeLimitsEnabled=False
bHeliAssistTurnCoordinationEnabled=False
bInvertYAxisMissile=False
bWeaponSwitchOnDepleted=False
bInvertC4Input=False
bGamepadInvertYAxisInfantry=False
bGamepadInvertYAxisLandVehicles=False
bGamepadInvertYAxisHelicopters=False
bGamepadInvertYAxisMissile=False
bGamepadLookAccelerationEnabled=True
LookAccelerationCurveType=Standard
LookAccelMagnitudeThreshold=0.900000
LookAccelPitchWeight=0.200000
LookAccelMaxMultiplier=1.600000
MoveStickPreset=Medium
MoveStickCentreMultiplier=15.000000
MoveStickAxialMultiplier=15.000000
MoveStickMaxInputMultiplier=15.000000
LookStickPreset=Medium
LookStickCentreMultiplier=15.000000
LookStickAxialMultiplier=15.000000
LookStickMaxInputMultiplier=15.000000
TriggersPreset=None
LeftTriggerMinMultiplier=0.000000
LeftTriggerMaxMultiplier=100.000000
RightTriggerMinMultiplier=0.000000
RightTriggerMaxMultiplier=100.000000
bRotaryMouseInputEnabled=True
RotaryMouseXFunction=Roll
RotaryMouseYFunction=Pitch
RotaryMouseAxisIsolation=0.000000
RotaryMousePitchSensitivity=100.000000
RotaryMouseRollSensitivity=100.000000
RotaryMouseYawSensitivity=50.000000
bLandMouseInputEnabled=False
bMissileMouseInputEnabled=True
GamepadLandVehicleSensitivityMultiplier=0.500000
GamepadAirVehicleSensitivityMultiplier=0.500000
GamepadAimAssistStrengthMultiplier=1.000000
GamepadResponseCurveType=Standard
GamepadButtonConfigInfantry=(TagName="Input.Gamepad.Config.Button.Infantry.Default")
GamepadAxisConfigInfantry=(TagName="Input.Gamepad.Config.Axis.Default")
GamepadButtonConfigGroundVehicle=(TagName="Input.Gamepad.Config.Button.Vehicle.Ground.Default")
GamepadAxisConfigGroundVehicle=(TagName="Input.Gamepad.Config.Axis.Default")
GamepadButtonConfigHelicopter=(TagName="Input.Gamepad.Config.Button.Vehicle.Air.Helicopter.Default")
GamepadAxisConfigHelicopter=(TagName="Input.Gamepad.Config.Axis.Default")
ActionBehaviors=(((TagName="UserSettings.Controls.ActionBehavior.Crouch"), Hold),((TagName="UserSettings.Controls.ActionBehavior.Prone"), Toggle),((TagName="UserSettings.Controls.ActionBehavior.Slide"), Hold),((TagName="UserSettings.Controls.ActionBehavior.Sprint"), Hold),((TagName="UserSettings.Controls.ActionBehavior.SlowWalk"), Hold),((TagName="UserSettings.Controls.ActionBehavior.ADS"), Hold),((TagName="UserSettings.Controls.ActionBehavior.Lean"), Hold),((TagName="UserSettings.Controls.ActionBehavior.Steady"), Hold),((TagName="UserSettings.Controls.ActionBehavior.Interact"), Hold),((TagName="UserSettings.Controls.ActionBehavior.Tip"), Toggle),((TagName="UserSettings.Controls.ActionBehavior.Gamepad.ADS"), Hold),((TagName="UserSettings.Controls.ActionBehavior.Gamepad.Lean"), Hold),((TagName="UserSettings.Controls.ActionBehavior.Gamepad.Steady"), Hold),((TagName="UserSettings.Controls.ActionBehavior.Gamepad.Crouch"), Toggle))
Language=en
HUDGlobalVisibilityType=On
HUDVisibilityTypes=(((TagName="UI.HUD.Element.SessionCash"), On),((TagName="UI.HUD.Element.CentralFeedback"), On),((TagName="UI.HUD.Element.Chatbox"), On),((TagName="UI.HUD.Element.Compass"), On),((TagName="UI.HUD.Element.EquippedItem"), On),((TagName="UI.HUD.Element.EventFeed"), On),((TagName="UI.HUD.Element.RewardFeed"), On),((TagName="UI.HUD.Element.FactionIcon"), On),((TagName="UI.HUD.Element.GameModeStatus"), On),((TagName="UI.HUD.Element.Health"), On),((TagName="UI.HUD.Element.Killfeed"), On),((TagName="UI.HUD.Element.LocationContext"), On),((TagName="UI.HUD.Element.Minimap"), On),((TagName="UI.HUD.Element.NetStatus"), On),((TagName="UI.HUD.Element.Falling"), On),((TagName="UI.HUD.Element.Vehicle.Passengers"), On),((TagName="UI.HUD.Element.PromotionToast"), On),((TagName="UI.HUD.Element.Vehicle.InputPrompt"), On),((TagName="UI.HUD.Element.QuickSlots"), On),((TagName="UI.HUD.Element.SpatialTrackers"), On),((TagName="UI.HUD.Element.Tipping"), On),((TagName="UI.HUD.Element.Vehicle.Name"), On),((TagName="UI.HUD.Element.Vehicle.FuelHealth"), On),((TagName="UI.HUD.Element.Vehicle.TelemetryDisplay.Land"), On),((TagName="UI.HUD.Element.Vehicle.TelemetryDisplay.Land.Gunner"), On),((TagName="UI.HUD.Element.Vehicle.TelemetryDisplay.Rotary"), On),((TagName="UI.HUD.Element.Vehicle.VehicleGradient"), On),((TagName="UI.HUD.Element.Vehicle.State"), On),((TagName="UI.HUD.Element.Vehicle.ThreatIndicator"), On),((TagName="UI.HUD.Element.Vehicle.Crosshair"), On),((TagName="UI.HUD.Element.Vehicle.FlightDisplay"), On),((TagName="UI.HUD.Element.Vehicle.BulletSpread"), On),((TagName="UI.HUD.Element.Vehicle.Weapon.Ammo"), On),((TagName="UI.HUD.Element.Vehicle.SpawnVehicleInformation"), On),((TagName="UI.HUD.Element.Vehicle.Flares"), On),((TagName="UI.HUD.Element.Vehicle.SupplyCrate"), On))
SelectedServerRegions=("eu-west")
bBackgroundFramesLimitEnabled=True
MinMaxBufferSize=5.000000
ScalabilityVersion=30
CustomVersion=3
FieldOfView=110.000000
CachedGPUBenchMarkResult=486.521362
Brightness=2.610000
NvidiaReflexMode=1
NvidiaDLSSMode=2
NvidiaDLSSGMode=0
Sharpness=1.220000
UpscalingMethod=XeSS
XeSSQualityMode=2
FSR3QualityMode=1
bUseMotionBlur=False
bUseDepthOfField=False
bUseLensFlare=False
bUseBloom=False
AudioOutputDevice="{0.0.0.00000000}.{342291ba-6335-4d88-a905-55a7d32f7b41}"
MasterVolume=0.630000
IngameMusicVolume=1.000000
MenuMusicVolume=1.000000
EffectsVolume=1.000000
UIVolume=1.000000
VOIPVolume=1.000000
VOIPProximityVolume=1.000000
VOIPSquadVolume=0.750000
bEnableSoundInBackground=False
MouseAcceleration=0.000000
MouseSensitivity=0.280000
MouseVerticalAxisSensitivityMultiplier=1.000000
GamepadHorizontalAxisSensitivity=3.000000
GamepadVerticalAxisSensitivity=2.000000
bUseVSync=False
bUseDynamicResolution=False
ResolutionSizeX=1920
ResolutionSizeY=1080
LastUserConfirmedResolutionSizeX=1920
LastUserConfirmedResolutionSizeY=1080
FullscreenMode=0
LastConfirmedFullscreenMode=0
PreferredFullscreenMode=0
Version=5
AudioQualityLevel=0
LastConfirmedAudioQualityLevel=0
FrameRateLimit=0.000000
DesiredScreenWidth=1920
DesiredScreenHeight=1080
LastUserConfirmedDesiredScreenWidth=1920
LastUserConfirmedDesiredScreenHeight=1080
LastRecommendedScreenWidth=-1.000000
LastRecommendedScreenHeight=-1.000000
LastCPUBenchmarkResult=226.064590
LastGPUBenchmarkResult=486.521362
LastCPUBenchmarkSteps=261.451355
LastCPUBenchmarkSteps=202.473404
LastGPUBenchmarkSteps=725.163330
LastGPUBenchmarkSteps=330.928284
LastGPUBenchmarkSteps=479.684937
LastGPUBenchmarkSteps=509.255554
LastGPUBenchmarkSteps=195.919739
LastGPUBenchmarkSteps=539.221985
LastGPUBenchmarkSteps=344.354675
LastGPUBenchmarkMultiplier=1.000000
bUseHDRDisplayOutput=False
HDRDisplayOutputNits=1000
SelectedServerBrowserFilters=(GameplayTags=((TagName="UI.Features.ServerBrowser.Filter.ShowOfficialServers"),(TagName="UI.Features.ServerBrowser.Filter.ShowPasswordProtectedServers"),(TagName="UI.Features.ServerBrowser.Filter.ShowNonPasswordProtectedServers"),(TagName="UI.Features.ServerBrowser.Filter.ShowFullServers")))
bHasSavedServerBrowserFilters=True
BackgroundFrameRateLimit=61.000000
bMigratedHeliAssistDefaults=True
WindowPositions=(X=0,Y=0)
SelectedServerBrowserAdvancedFilters=(_aaaamboiamjdifamhpnig=,_aaaamfcgncbkkgoohjclc=(GameplayTags=((TagName="Server.Descriptor.Hardcore"))))
bHasSavedServerBrowserAdvancedFilters=True

[/Script/Engine.GameUserSettings]
bUseDesiredScreenHeight=False

[/Script/WDJoystick.WDJoystickSettings]
Roll=(DeviceIdentifier="",_aaaajcpgpllhacnlfdnkg=0,bInvert=False,_aaaalddpkcdlnfnaagdkl=False,Positive=(DeviceIdentifier="",_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),Negative=(DeviceIdentifier="",_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),_aaaaoabiaaaacohedinbn=1.000000,_aaabgcjobaejlnkbppedn=False,_aaaaombggppmmijkohdph=(DeviceIdentifier="",_aaaajcpgpllhacnlfdnkg=-1,_aaaajlbldnobdplelbhhg=0.500000,_aaaakbblnlfadfmofnkml=True,_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),_aaaaochdddlogkjceogmo=(DeviceIdentifier="",_aaaajcpgpllhacnlfdnkg=-1,_aaaajlbldnobdplelbhhg=0.500000,_aaaakbblnlfadfmofnkml=True,_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),Sensitivity=1.000000,DeadZone=0.050000)
Pitch=(DeviceIdentifier="",_aaaajcpgpllhacnlfdnkg=1,bInvert=False,_aaaalddpkcdlnfnaagdkl=False,Positive=(DeviceIdentifier="",_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),Negative=(DeviceIdentifier="",_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),_aaaaoabiaaaacohedinbn=1.000000,_aaabgcjobaejlnkbppedn=False,_aaaaombggppmmijkohdph=(DeviceIdentifier="",_aaaajcpgpllhacnlfdnkg=-1,_aaaajlbldnobdplelbhhg=0.500000,_aaaakbblnlfadfmofnkml=True,_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),_aaaaochdddlogkjceogmo=(DeviceIdentifier="",_aaaajcpgpllhacnlfdnkg=-1,_aaaajlbldnobdplelbhhg=0.500000,_aaaakbblnlfadfmofnkml=True,_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),Sensitivity=1.000000,DeadZone=0.050000)
Yaw=(DeviceIdentifier="",_aaaajcpgpllhacnlfdnkg=5,bInvert=False,_aaaalddpkcdlnfnaagdkl=False,Positive=(DeviceIdentifier="",_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),Negative=(DeviceIdentifier="",_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),_aaaaoabiaaaacohedinbn=1.000000,_aaabgcjobaejlnkbppedn=False,_aaaaombggppmmijkohdph=(DeviceIdentifier="",_aaaajcpgpllhacnlfdnkg=-1,_aaaajlbldnobdplelbhhg=0.500000,_aaaakbblnlfadfmofnkml=True,_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),_aaaaochdddlogkjceogmo=(DeviceIdentifier="",_aaaajcpgpllhacnlfdnkg=-1,_aaaajlbldnobdplelbhhg=0.500000,_aaaakbblnlfadfmofnkml=True,_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),Sensitivity=1.000000,DeadZone=0.050000)
Throttle=(DeviceIdentifier="",_aaaajcpgpllhacnlfdnkg=2,bInvert=False,_aaaalddpkcdlnfnaagdkl=False,Positive=(DeviceIdentifier="",_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),Negative=(DeviceIdentifier="",_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),_aaaaoabiaaaacohedinbn=1.000000,_aaabgcjobaejlnkbppedn=False,_aaaaombggppmmijkohdph=(DeviceIdentifier="",_aaaajcpgpllhacnlfdnkg=-1,_aaaajlbldnobdplelbhhg=0.500000,_aaaakbblnlfadfmofnkml=True,_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),_aaaaochdddlogkjceogmo=(DeviceIdentifier="",_aaaajcpgpllhacnlfdnkg=-1,_aaaajlbldnobdplelbhhg=0.500000,_aaaakbblnlfadfmofnkml=True,_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),Sensitivity=1.000000,DeadZone=0.050000)
LookYaw=(DeviceIdentifier="",_aaaajcpgpllhacnlfdnkg=-1,bInvert=False,_aaaalddpkcdlnfnaagdkl=False,Positive=(DeviceIdentifier="",_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),Negative=(DeviceIdentifier="",_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),_aaaaoabiaaaacohedinbn=1.000000,_aaabgcjobaejlnkbppedn=False,_aaaaombggppmmijkohdph=(DeviceIdentifier="",_aaaajcpgpllhacnlfdnkg=-1,_aaaajlbldnobdplelbhhg=0.500000,_aaaakbblnlfadfmofnkml=True,_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),_aaaaochdddlogkjceogmo=(DeviceIdentifier="",_aaaajcpgpllhacnlfdnkg=-1,_aaaajlbldnobdplelbhhg=0.500000,_aaaakbblnlfadfmofnkml=True,_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),Sensitivity=1.000000,DeadZone=0.050000)
LookPitch=(DeviceIdentifier="",_aaaajcpgpllhacnlfdnkg=-1,bInvert=False,_aaaalddpkcdlnfnaagdkl=False,Positive=(DeviceIdentifier="",_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),Negative=(DeviceIdentifier="",_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),_aaaaoabiaaaacohedinbn=1.000000,_aaabgcjobaejlnkbppedn=False,_aaaaombggppmmijkohdph=(DeviceIdentifier="",_aaaajcpgpllhacnlfdnkg=-1,_aaaajlbldnobdplelbhhg=0.500000,_aaaakbblnlfadfmofnkml=True,_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),_aaaaochdddlogkjceogmo=(DeviceIdentifier="",_aaaajcpgpllhacnlfdnkg=-1,_aaaajlbldnobdplelbhhg=0.500000,_aaaakbblnlfadfmofnkml=True,_aaaaljahlggohoapfcfef=-1,_aaaaidddockpolojoodpb=-1,_aaaamdcclmobefllhjkdm=Up),Sensitivity=1.000000,DeadZone=0.050000)

[/Script/BHEnhancedInput.BHEnhancedInputPlayerBinds]
CustomKeybindings=(((TagName="UI.Action.Feature.PingWheel.ToggleScene"), (PrimaryKey=(Key=ThumbMouseButton,bIsCustom=True),SecondaryKey=(bIsCustom=True))),((TagName="Input.NamedActions.Player.Crouch"), (PrimaryKey=(Key=LeftControl,bIsCustom=True))),((TagName="Input.NamedActions.Player.Prone"), (PrimaryKey=(Key=Z,bIsCustom=True))),((TagName="Input.NamedActions.Ping"), (PrimaryKey=(Key=ThumbMouseButton,bIsCustom=True))),((TagName="Input.NamedActions.Player.Traversing.Climbing.Cancel"), (PrimaryKey=(bIsCustom=True))),((TagName="Input.NamedActions.Vehicle.WeaponExtension.Change.3"), (PrimaryKey=(bIsCustom=True))),((TagName="Input.NamedActions.Vehicle.Collective.Raise"), (PrimaryKey=(Key=W,bIsCustom=True))),((TagName="Input.NamedActions.Vehicle.Collective.Lower"), (PrimaryKey=(Key=S,bIsCustom=True))),((TagName="Input.NamedActions.Vehicle.Cyclic.X.Positive"), (PrimaryKey=(Key=LeftShift,bIsCustom=True))),((TagName="Input.NamedActions.Vehicle.Cyclic.X.Negative"), (PrimaryKey=(Key=LeftControl,bIsCustom=True))),((TagName="Input.NamedActions.HoldableItem.Weapon.CycleFireMode"), (PrimaryKey=(Key=MiddleMouseButton,bIsCustom=True))),((TagName="Input.NamedActions.Inventory.Change.4"), (PrimaryKey=(Key=Four),SecondaryKey=(Key=LeftAlt,bIsCustom=True))),((TagName="Input.NamedActions.Inventory.Change.5"), (PrimaryKey=(Key=Five),SecondaryKey=(Key=CapsLock,bIsCustom=True))),((TagName="Input.NamedActions.Player.SlideDownLadder"), (PrimaryKey=(bIsCustom=True))),((TagName="Input.NamedActions.Player.JumpOffLadder"), (PrimaryKey=(bIsCustom=True))),((TagName="Input.NamedActions.Player.FastSwim"), (PrimaryKey=(bIsCustom=True))))

[/Script/BHUserSettings.BHKeybindingSourceCommonUI]
CustomKeybindings=(Tag=(TagName="UI.Action.Feature.PingWheel.ToggleScene"),_aaaagidmmklpggjklakpi=((Key=ThumbMouseButton),()))

[WDSecondStage]
FirstSessionTimestamp=2026-09-10T17:43:18.908Z

